# Generated by Django 5.1.6 on 2025-02-24 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='create_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 2, 24, 2, 12, 33, 880226, tzinfo=datetime.timezone.utc)),
        ),
    ]
